services:
  nginx:
    image: nginx:latest
    volumes:
      - ./dev/nginx/nginx.conf:/etc/nginx/nginx.conf
  dns:
    image: jpillora/dnsmasq:latest
    container_name: whaleshock-dev-dns
    restart: unless-stopped
    ports:
      - "53:53/udp"
    volumes:
      - ./dev/dns/dnsmasq.conf:/etc/dnsmasq.conf