services:
  nginx:
    image: nginx:latest
    container_name: whaleshock-reverse-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./letsencrypt:/etc/letsencrypt
volumes:
  letsencrypt: